version: '3.2'

services:
    postgres:
        container_name: postgres
        image: postgres:12.3-alpine
        restart: always
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: dev
            POSTGRES_PASSWORD: password
            POSTGRES_DB: postgres
        ports:
            - '5432:5432'
        networks:
            - network

    package1:
      image: "node:14"
      user: "node"
      working_dir: /home/node/app
      environment:
        - NODE_ENV=test
        - LOG_LEVEL=info
      volumes:
        - ./package1 :/home/node/app
      ports:
        - "4000:4000"
      depends_on:
        - postgres
      links:
        - postgres
      command: "ls"

networks:
    network:
        driver: bridge
