name: 'CRON'
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/* * * * *'
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo Hello World
