name: Create new version
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
        default: "0.0.0"
      title:
        description: "Title of the version"
        required: false

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ github.event.inputs.version }}!"
          echo "- in ${{ github.event.inputs.title }}!"
