name: Package 1
on:
  push:
    paths:
      - 'package1/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install
        working-directory: package1
        run: npm install

      - name: DockerCompose Up
        run: docker-compose up --exit-code-from package2 postgres package1


