name: test-integration
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install
        run: npm install
      - name: DockerCompose Up
        run: docker-compose up --exit-code-from package1

